/*
 * Sales Order - Create, Read, Update, Delete (A2X)
 * You can use this service to integrate external  applications with sales order processing in SAP  S/4HANA Cloud. In every API call, you can make  use of the following operations:  - You can retrieve  sales orders. Apply any of the filters provided or  retrieve all existing data.  - You can create sales  orders. Note that you must use “deep insert”  requests (a header plus the following entities:  header partner, header pricing element, header  text, payment details, item, item partner, item  pricing element, and item text). You cannot create  entities without including any related entities.  - For  existing sales orders, you can create new items.  Note that you must use “deep insert” requests  (with the following entities: item partner, item pricing  element, and item text). You cannot create entities  without including any related entities.  - For existing  sales orders, you can update the header, header  partner, header pricing element, header text,  payment details, item, item partner, item pricing  element, and item text.  - For existing sales  orders, you can delete the header, header partner,  header pricing element, header text, payment  details, item, item partner, item pricing element,  and item text.  - You can accept or deny approval  requests for sales orders that cannot be processed  without the consent of an approver.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_sales_order_srv.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Sales Order Schedule Line (API)
 */
@ApiModel(description = "Sales Order Schedule Line (API)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-25T07:18:58.114Z")
public class APISALESORDERSRVASalesOrderScheduleLineType {
  @SerializedName("SalesOrder")
  private String salesOrder = null;

  @SerializedName("SalesOrderItem")
  private String salesOrderItem = null;

  @SerializedName("ScheduleLine")
  private String scheduleLine = null;

  public APISALESORDERSRVASalesOrderScheduleLineType salesOrder(String salesOrder) {
    this.salesOrder = salesOrder;
    return this;
  }

   /**
   * The number that uniquely identifies the sales document.
   * @return salesOrder
  **/
  @ApiModelProperty(value = "The number that uniquely identifies the sales document.")
  public String getSalesOrder() {
    return salesOrder;
  }

  public void setSalesOrder(String salesOrder) {
    this.salesOrder = salesOrder;
  }

  public APISALESORDERSRVASalesOrderScheduleLineType salesOrderItem(String salesOrderItem) {
    this.salesOrderItem = salesOrderItem;
    return this;
  }

   /**
   * The number that uniquely identifies the item in the sales document.
   * @return salesOrderItem
  **/
  @ApiModelProperty(value = "The number that uniquely identifies the item in the sales document.")
  public String getSalesOrderItem() {
    return salesOrderItem;
  }

  public void setSalesOrderItem(String salesOrderItem) {
    this.salesOrderItem = salesOrderItem;
  }

  public APISALESORDERSRVASalesOrderScheduleLineType scheduleLine(String scheduleLine) {
    this.scheduleLine = scheduleLine;
    return this;
  }

   /**
   * The number that uniquely identifies the schedule line in the sales document.   When an item has more than one schedule line, the system automatically assigns a unique number to each line. The number is displayed in the details screens for schedule lines.The schedule line number serves internal purposes and does not, for example, determine the sequence of schedule lines in the overview screen. The schedule lines on the overview screen are sorted by date.
   * @return scheduleLine
  **/
  @ApiModelProperty(value = "The number that uniquely identifies the schedule line in the sales document.   When an item has more than one schedule line, the system automatically assigns a unique number to each line. The number is displayed in the details screens for schedule lines.The schedule line number serves internal purposes and does not, for example, determine the sequence of schedule lines in the overview screen. The schedule lines on the overview screen are sorted by date.")
  public String getScheduleLine() {
    return scheduleLine;
  }

  public void setScheduleLine(String scheduleLine) {
    this.scheduleLine = scheduleLine;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APISALESORDERSRVASalesOrderScheduleLineType apISALESORDERSRVASalesOrderScheduleLineType = (APISALESORDERSRVASalesOrderScheduleLineType) o;
    return Objects.equals(this.salesOrder, apISALESORDERSRVASalesOrderScheduleLineType.salesOrder) &&
        Objects.equals(this.salesOrderItem, apISALESORDERSRVASalesOrderScheduleLineType.salesOrderItem) &&
        Objects.equals(this.scheduleLine, apISALESORDERSRVASalesOrderScheduleLineType.scheduleLine);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salesOrder, salesOrderItem, scheduleLine);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APISALESORDERSRVASalesOrderScheduleLineType {\n");
    
    sb.append("    salesOrder: ").append(toIndentedString(salesOrder)).append("\n");
    sb.append("    salesOrderItem: ").append(toIndentedString(salesOrderItem)).append("\n");
    sb.append("    scheduleLine: ").append(toIndentedString(scheduleLine)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

