/*
 * Sales Order - Create, Read, Update, Delete (A2X)
 * You can use this service to integrate external  applications with sales order processing in SAP  S/4HANA Cloud. In every API call, you can make  use of the following operations:  - You can retrieve  sales orders. Apply any of the filters provided or  retrieve all existing data.  - You can create sales  orders. Note that you must use “deep insert”  requests (a header plus the following entities:  header partner, header pricing element, header  text, payment details, item, item partner, item  pricing element, and item text). You cannot create  entities without including any related entities.  - For  existing sales orders, you can create new items.  Note that you must use “deep insert” requests  (with the following entities: item partner, item pricing  element, and item text). You cannot create entities  without including any related entities.  - For existing  sales orders, you can update the header, header  partner, header pricing element, header text,  payment details, item, item partner, item pricing  element, and item text.  - For existing sales  orders, you can delete the header, header partner,  header pricing element, header text, payment  details, item, item partner, item pricing element,  and item text.  - You can accept or deny approval  requests for sales orders that cannot be processed  without the consent of an approver.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_sales_order_srv.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.api_sales_order_srv.model.APISALESORDERSRVASalesOrderItemType;
import com.sap.apibhub.sdk.api_sales_order_srv.model.APISALESORDERSRVASalesOrderType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Sales Order Item Partner (API)
 */
@ApiModel(description = "Sales Order Item Partner (API)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-25T07:18:58.114Z")
public class APISALESORDERSRVASalesOrderItemPartnerType {
  @SerializedName("SalesOrder")
  private String salesOrder = null;

  @SerializedName("SalesOrderItem")
  private String salesOrderItem = null;

  @SerializedName("PartnerFunction")
  private String partnerFunction = null;

  @SerializedName("to_SalesOrder")
  private APISALESORDERSRVASalesOrderType toSalesOrder = null;

  @SerializedName("to_SalesOrderItem")
  private APISALESORDERSRVASalesOrderItemType toSalesOrderItem = null;

  public APISALESORDERSRVASalesOrderItemPartnerType salesOrder(String salesOrder) {
    this.salesOrder = salesOrder;
    return this;
  }

   /**
   * Sales Order
   * @return salesOrder
  **/
  @ApiModelProperty(value = "Sales Order")
  public String getSalesOrder() {
    return salesOrder;
  }

  public void setSalesOrder(String salesOrder) {
    this.salesOrder = salesOrder;
  }

  public APISALESORDERSRVASalesOrderItemPartnerType salesOrderItem(String salesOrderItem) {
    this.salesOrderItem = salesOrderItem;
    return this;
  }

   /**
   * Sales Order Item
   * @return salesOrderItem
  **/
  @ApiModelProperty(value = "Sales Order Item")
  public String getSalesOrderItem() {
    return salesOrderItem;
  }

  public void setSalesOrderItem(String salesOrderItem) {
    this.salesOrderItem = salesOrderItem;
  }

  public APISALESORDERSRVASalesOrderItemPartnerType partnerFunction(String partnerFunction) {
    this.partnerFunction = partnerFunction;
    return this;
  }

   /**
   * The abbreviated form of the name that identifies the partner function.
   * @return partnerFunction
  **/
  @ApiModelProperty(value = "The abbreviated form of the name that identifies the partner function.")
  public String getPartnerFunction() {
    return partnerFunction;
  }

  public void setPartnerFunction(String partnerFunction) {
    this.partnerFunction = partnerFunction;
  }

  public APISALESORDERSRVASalesOrderItemPartnerType toSalesOrder(APISALESORDERSRVASalesOrderType toSalesOrder) {
    this.toSalesOrder = toSalesOrder;
    return this;
  }

   /**
   * Get toSalesOrder
   * @return toSalesOrder
  **/
  @ApiModelProperty(value = "")
  public APISALESORDERSRVASalesOrderType getToSalesOrder() {
    return toSalesOrder;
  }

  public void setToSalesOrder(APISALESORDERSRVASalesOrderType toSalesOrder) {
    this.toSalesOrder = toSalesOrder;
  }

  public APISALESORDERSRVASalesOrderItemPartnerType toSalesOrderItem(APISALESORDERSRVASalesOrderItemType toSalesOrderItem) {
    this.toSalesOrderItem = toSalesOrderItem;
    return this;
  }

   /**
   * Get toSalesOrderItem
   * @return toSalesOrderItem
  **/
  @ApiModelProperty(value = "")
  public APISALESORDERSRVASalesOrderItemType getToSalesOrderItem() {
    return toSalesOrderItem;
  }

  public void setToSalesOrderItem(APISALESORDERSRVASalesOrderItemType toSalesOrderItem) {
    this.toSalesOrderItem = toSalesOrderItem;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APISALESORDERSRVASalesOrderItemPartnerType apISALESORDERSRVASalesOrderItemPartnerType = (APISALESORDERSRVASalesOrderItemPartnerType) o;
    return Objects.equals(this.salesOrder, apISALESORDERSRVASalesOrderItemPartnerType.salesOrder) &&
        Objects.equals(this.salesOrderItem, apISALESORDERSRVASalesOrderItemPartnerType.salesOrderItem) &&
        Objects.equals(this.partnerFunction, apISALESORDERSRVASalesOrderItemPartnerType.partnerFunction) &&
        Objects.equals(this.toSalesOrder, apISALESORDERSRVASalesOrderItemPartnerType.toSalesOrder) &&
        Objects.equals(this.toSalesOrderItem, apISALESORDERSRVASalesOrderItemPartnerType.toSalesOrderItem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salesOrder, salesOrderItem, partnerFunction, toSalesOrder, toSalesOrderItem);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APISALESORDERSRVASalesOrderItemPartnerType {\n");
    
    sb.append("    salesOrder: ").append(toIndentedString(salesOrder)).append("\n");
    sb.append("    salesOrderItem: ").append(toIndentedString(salesOrderItem)).append("\n");
    sb.append("    partnerFunction: ").append(toIndentedString(partnerFunction)).append("\n");
    sb.append("    toSalesOrder: ").append(toIndentedString(toSalesOrder)).append("\n");
    sb.append("    toSalesOrderItem: ").append(toIndentedString(toSalesOrderItem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

